# Seminar 3

In [1]:
print("Hello worlds!")

Hello worlds!


In [3]:
import numpy as np

In [4]:
b=[1,2,3]

In [5]:
b?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [6]:
b

[1, 2, 3]

In [7]:
?b

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [8]:
print?


Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [11]:
def suma(a,b):
    """
    functia calculeaza suma lui a si b
    params: a : primul numar
    param: b: al doilea numar
    """
    return a+b

In [12]:
suma(2,3)

5

In [13]:
suma?

Signature: suma(a, b)
Docstring:
functia calculeaza suma lui a si b
params: a : primul numar
param: b: al doilea numar
File:      c:\users\rodic\appdata\local\temp\ipykernel_8920\4053421948.py
Type:      function


In [15]:
a=4
# a=5
suma(a,6)

10

In [16]:
suma??

Signature: suma(a, b)
Source:   
def suma(a,b):
    """
    functia calculeaza suma lui a si b
    params: a : primul numar
    param: b: al doilea numar
    """
    return a+b
File:      c:\users\rodic\appdata\local\temp\ipykernel_8920\4053421948.py
Type:      function


In [17]:
%who

a	 b	 np	 suma	 


In [18]:
%whos

Variable   Type        Data/Info
--------------------------------
a          int         4
b          list        n=3
np         module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
suma       function    <function suma at 0x00000293A5F0E8B0>


In [19]:
%pwd

'C:\\Users\\rodic\\OneDrive\\FSEGA\\cursuri\\2022-2023\\si\\cod ore'

In [21]:
%timeit suma(1,2)

146 ns ± 22.1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## python

In [22]:
a=[1,2,3]

In [23]:
b=a

In [24]:
b

[1, 2, 3]

In [25]:
a.append(5)

In [26]:
a

[1, 2, 3, 5]

In [27]:
b

[1, 2, 3, 5]

In [28]:
c=a.copy()

In [29]:
c

[1, 2, 3, 5]

In [30]:
a[0]

1

In [31]:
a[0]=1000

In [32]:
a

[1000, 2, 3, 5]

In [33]:
b

[1000, 2, 3, 5]

In [34]:
c

[1, 2, 3, 5]

In [36]:
n=1053452436524624634565465464254353145134543543542353454354325243534

In [37]:
n

1053452436524624634565465464254353145134543543542353454354325243534

In [38]:
n/2

5.267262182623123e+65

In [39]:
5/3

1.6666666666666667

In [40]:
5//3

1

In [41]:
2**3

8

In [42]:
a='ceva text'

In [43]:
print(a)


ceva text


In [44]:
print(a,b)

ceva text [1000, 2, 3, 5]


In [45]:
print(a,b,c)

ceva text [1000, 2, 3, 5] [1, 2, 3, 5]


In [47]:
print(a+' alt text')

ceva text alt text


In [49]:
a=2345431
print(f'text care contine pe a={a}')

text care contine pe a=2345431


In [50]:
a='ceva text'

In [51]:
a[1]

'e'

In [52]:
a[1]='r'

TypeError: 'str' object does not support item assignment

In [53]:
a=4
if a<10:
    print(f'a={a} e mai mic decat 10')
else:
    print('nu e')

a=4 e mai mic decat 10


In [54]:
print(f'a={a} e mai mic decat 10') if a<10 else print('nu e')

a=4 e mai mic decat 10


In [58]:
a=25
if a<10:
    b=a*5
elif a<20:
    b=a*10
else:
    b=a*15
print(b)

375


In [59]:
c

[1, 2, 3, 5]

In [60]:
for el in c:
    print(el)

1
2
3
5


In [61]:
for index, el in enumerate(c):
    print(index, el)

0 1
1 2
2 3
3 5


In [64]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [66]:
for i in range(10):     print(i, i**2)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81


In [68]:
for i in range(10):
    if i<5:
        print(i,i**2)
    else:
        print(i,i**3)

0 0
1 1
2 4
3 9
4 16
5 125
6 216
7 343
8 512
9 729


In [69]:
for i in range(10): print(i, i**2) if i<5 else print(i,i**3)

0 0
1 1
2 4
3 9
4 16
5 125
6 216
7 343
8 512
9 729


## numpy

In [70]:
import numpy as np

In [71]:
a=[1,2,3]


In [72]:
type(a)


list

In [73]:
a=np.array(a)

In [74]:
a

array([1, 2, 3])

In [75]:
type(a)

numpy.ndarray

In [76]:
b=[[1,2,3],[4,5]]

In [77]:
b

[[1, 2, 3], [4, 5]]

In [78]:
c=[[1,2,3],[4,5,6]]

In [79]:
c

[[1, 2, 3], [4, 5, 6]]

In [80]:
c=np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
b=np.array(b)

C:\Users\rodic\AppData\Local\Temp\ipykernel_8920\1349102842.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array(b)


In [82]:
a.shape

(3,)

In [83]:
c.shape

(2, 3)

In [84]:
linii=c.shape[0]

In [85]:
linii

2

In [86]:
coloane=c.shape[1]
coloane

3

In [87]:
a.ndim

1

In [88]:
c.ndim

2

In [89]:
a.dtype

dtype('int32')

In [90]:
d=np.array([1.3, 4, 6])

In [91]:
d.dtype

dtype('float64')

In [92]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
a

array([1, 2, 3])

In [94]:
a[1]

2

In [95]:
c[1]

array([4, 5, 6])

In [96]:
a[1:]

array([2, 3])

In [97]:
a[:1]

array([1])

In [98]:
a[-1]

3

In [99]:
a[-2:]

array([2, 3])

In [101]:
c[1, -2:]

array([5, 6])

In [102]:
c[:,1]

array([2, 5])

In [103]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
c[:,1:]

array([[2, 3],
       [5, 6]])

In [105]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [108]:
np.zeros_like(c)

array([[0, 0, 0],
       [0, 0, 0]])

In [109]:
np.ones(4)

array([1., 1., 1., 1.])

In [110]:
np.ones_like(c)

array([[1, 1, 1],
       [1, 1, 1]])

In [111]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 4.62445445e-321, 6.95250701e-310,
       3.20558141e-317])

In [112]:
np.empty_like(c)

array([[-1572542752,         659,           0],
       [          0,      131074,           0]])

In [116]:
np.arange(30,10,-3)

array([30, 27, 24, 21, 18, 15, 12])

In [119]:
np.full((4,3), [6,1,3])

array([[6, 1, 3],
       [6, 1, 3],
       [6, 1, 3],
       [6, 1, 3]])

In [120]:
np.full_like(c,1000)

array([[1000, 1000, 1000],
       [1000, 1000, 1000]])

In [121]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
a

array([1, 2, 3])

In [129]:
a*a

array([1, 4, 9])

In [130]:
c*c

array([[ 1,  4,  9],
       [16, 25, 36]])

In [132]:
c**30

array([[          1,  1073741824, -1010140999],
       [          0,   433305513,  1073741824]], dtype=int32)

In [134]:
2**32

4294967296

In [135]:
9**30

42391158275216203514294433201

In [138]:
a=np.array([1.3, 9.4])

In [139]:
a**30

array([2.61999564e+03, 1.56255606e+29])

In [140]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
a

array([1.3, 9.4])

In [142]:
np.mean(a)

5.3500000000000005

In [143]:
np.mean(c)

3.5

In [144]:
np.mean(c, axis=0)

array([2.5, 3.5, 4.5])

In [145]:
np.mean(c, axis=1)

array([2., 5.])

In [ ]:
# np.median, np.sum