## Seminar 3

In [4]:
print("hello world")

hello world


In [5]:
print()

In [6]:
import numpy as np

In [7]:
b=[1,2,3]

In [8]:
b?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [9]:
b

[1, 2, 3]

In [10]:
?b

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [16]:
def suma(a,b):
    """
    functia calculeaza suma lui a si b
    """
    return a+b

In [13]:
suma(2,3)

5

In [17]:
suma?

Signature: suma(a, b)
Docstring: functia calculeaza suma lui a si b
File:      c:\users\bacik\appdata\local\temp\ipykernel_16808\4022257478.py
Type:      function


In [18]:
a=4
a=6
suma(a,5)

11

In [19]:
suma??

Signature: suma(a, b)
Source:   
def suma(a,b):
    """
    functia calculeaza suma lui a si b
    """
    return a+b
File:      c:\users\bacik\appdata\local\temp\ipykernel_16808\4022257478.py
Type:      function


In [20]:
%who

a	 b	 np	 suma	 


In [21]:
%pwd

'C:\\Users\\bacik\\Documents\\Statistica'

In [22]:
%TIMEIT SUMA(1,3)

UsageError: Line magic function `%TIMEIT` not found.


In [23]:
%timeit suma(2,3)

109 ns ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## python

In [26]:
a?

Type:        int
String form: 6
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4


In [27]:
?a

Type:        int
String form: 6
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4


In [37]:
a=[1,2,3]

In [29]:
b=a

In [38]:
a.append(5)

In [39]:
a

[1, 2, 3, 5]

## numpy

In [43]:
import numpy as np

In [44]:
a=[1,2,3]

In [45]:
a=np.array(a)

In [46]:
a

array([1, 2, 3])

In [47]:
type(a)

numpy.ndarray

In [49]:
b=[[1,2,3],[4,5]]

In [50]:
b

[[1, 2, 3], [4, 5]]

In [51]:
c=[[1,2,3], [4,5,6]]

In [52]:
c

[[1, 2, 3], [4, 5, 6]]

In [53]:
c=np.array(c)

In [54]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
c.shape

(2, 3)

In [56]:
linii=c.shape[0]

In [57]:
linii

2

In [58]:
a.dtype

dtype('int32')

In [59]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a

array([1, 2, 3])