In [1]:
print("Hello, world!")

Hello, world!


In [2]:
print()

In [3]:
import numpy as np

In [4]:
b=[1,2,3]

In [5]:
b

[1, 2, 3]

In [6]:
?b

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [7]:
def sum(a,b):
    return a+b

In [10]:
def suma(a,b):
    """
    Functia calculeaza suma lui a si b.
    params: a -- primul nr
            b -- al doilea nr
    """
    return a+b

In [9]:
suma(2,3)

5

In [11]:
suma?

Signature: suma(a, b)
Docstring:
Functia calculeaza suma lui a si b.
params: a -- primul nr
        b -- al doilea nr
File:      c:\users\damaris\appdata\local\temp\ipykernel_38640\1610827563.py
Type:      function


In [12]:
a=4
# a=5 ctrl+slash
suma(a,6)

10

In [13]:
%who # variabile si parametrii incarcati

No variables match your requested type.


In [14]:
%who

a	 b	 np	 sum	 suma	 


In [15]:
%whos

Variable   Type        Data/Info
--------------------------------
a          int         4
b          list        n=3
np         module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sum        function    <function sum at 0x0000027A4E65A160>
suma       function    <function suma at 0x0000027A5014F040>


In [19]:
%pwd
# working directory

'C:\\Users\\Damaris\\Seminar SIDC'

In [18]:
%pwd

'C:\\Users\\Damaris\\Seminar SIDC'

In [20]:
%timeit suma(1,2)

138 ns ± 14.7 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


python

In [21]:
a=[1,2,3]

In [22]:
b=a

In [23]:
b

[1, 2, 3]

In [24]:
a.append(5)

In [25]:
a

[1, 2, 3, 5]

In [26]:
b

[1, 2, 3, 5]

In [27]:
c=a.copy()

In [29]:
a[0]=1000

In [30]:
a

[1000, 2, 3, 5]

In [31]:
c

[1, 2, 3, 5]

In [32]:
b

[1000, 2, 3, 5]

In [35]:
n=10938203820358320582

In [36]:
n

10938203820358320582

In [37]:
n/2

5.46910191017916e+18

In [38]:
# nr intreg

In [39]:
5//3

1

In [40]:
2**5

32

In [41]:
a='ceva text'

In [42]:
print(a)

ceva text


In [43]:
print(a,b,c)

ceva text [1000, 2, 3, 5] [1, 2, 3, 5]


In [45]:
a=24
print(f'text care contine a={a}')

text care contine a=24


In [46]:
a=4
if a<10:
    print(f'a={a} e mai mic decat 10')
else:
    print(f'nu')

a=4 e mai mic decat 10


In [47]:
print(f'a={a} e mai mic decat 10') if a<10 else print('nu e')

a=4 e mai mic decat 10


In [49]:
if a<10:
    b=a*5
elif a<29:
    b=a*10
else:
    b=a*15
print(b)

20


In [50]:
for el in c:
    print(el)

1
2
3
5


In [51]:
for index, el in enumerate(c):
    print(index, el)

0 1
1 2
2 3
3 5


In [53]:
list(range(10))
# limita superioara nu este inclusa in lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
for i in range(10):
    print(i, i**2)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81


In [55]:
for i in range(10):
    if i<5:
        print(i, i**2)
    else:
        print(i, i**3)

0 0
1 1
2 4
3 9
4 16
5 125
6 216
7 343
8 512
9 729


In [56]:
for i in range(10): print(i, i**2) if i<5 else print(i, i**3)

0 0
1 1
2 4
3 9
4 16
5 125
6 216
7 343
8 512
9 729


numpy

In [57]:
import numpy as np

In [58]:
a=[1,2,3]

In [59]:
type(a)

list

In [60]:
a=np.array(a)

In [61]:
a

array([1, 2, 3])

In [62]:
type(a)

numpy.ndarray

In [63]:
# lista bidimensionala
b=[[1,2,3],[4,5]]

In [64]:
b

[[1, 2, 3], [4, 5]]

In [65]:
c=[[1,2,3],[4,5,6]]

In [66]:
c

[[1, 2, 3], [4, 5, 6]]

In [67]:
type(c)

list

In [68]:
c=np.array(c)

In [69]:
type(c)

numpy.ndarray

In [70]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
# dimensiunea
a.shape

(3,)

In [73]:
# tuplu
c.shape

(2, 3)

In [75]:
linii=c.shape[0]

In [76]:
linii

2

In [77]:
coloane=c.shape[1]

In [78]:
coloane

3

In [79]:
a.ndim

1

In [80]:
c.ndim

2

In [81]:
# tip de date
a.dtype

dtype('int32')

In [82]:
d=np.array([1.3, 4, 6])

In [83]:
d.dtype

dtype('float64')

In [84]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
a

array([1, 2, 3])

In [86]:
a[1]

2

In [87]:
c[1]

array([4, 5, 6])

In [88]:
a[1:]

array([2, 3])

In [89]:
a[:2]

array([1, 2])

In [91]:
# last element
a[-1]

3

In [93]:
a[-2:]

array([2, 3])

In [95]:
# ultimele doua elemente de pe linia intai
c[1, -2:]

array([5, 6])

In [96]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
c[:,1]

array([2, 5])

In [98]:
c[:,1:]

array([[2, 3],
       [5, 6]])

In [99]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [102]:
# 2 matrici de 3x4
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [103]:
np.zeros_like(c)

array([[0, 0, 0],
       [0, 0, 0]])

In [104]:
np.ones(4)

array([1., 1., 1., 1.])

In [105]:
np.ones_like(c)

array([[1, 1, 1],
       [1, 1, 1]])

In [106]:
np.empty(5)

array([1.34595274e-311, 1.34597698e-311, 1.34597685e-311, 1.34595329e-311,
       1.27587198e-152])

In [107]:
np.empty_like(c)

array([[6488161, 7209071, 6357092],
       [3866675, 3801155, 5570652]])

In [111]:
# range equivalent; limite + pas
np.arange(30,10,-3)

array([30, 27, 24, 21, 18, 15, 12])

In [112]:
np.full(4, 6)

array([6, 6, 6, 6])

In [114]:
np.full((4,3), [6,1,3])

array([[6, 1, 3],
       [6, 1, 3],
       [6, 1, 3],
       [6, 1, 3]])

In [115]:
np.full_like(c,1000)

array([[1000, 1000, 1000],
       [1000, 1000, 1000]])

In [116]:
b

[[1, 2, 3], [4, 5]]

In [117]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
a

array([1, 2, 3])

In [119]:
a+5

array([6, 7, 8])

In [120]:
c**3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [121]:
a=np.array([1.3, 3.4])

In [122]:
a**50

array([4.97929223e+05, 3.74926253e+26])

In [123]:
np.mean(a)

2.35

In [126]:
# media tuturor elementelor matricei
np.mean(c)

3.5

In [127]:
np.mean(c, axis=0)

array([2.5, 3.5, 4.5])

In [128]:
# np.median, np.sum